In [5]:
import torch
import numpy as np
import os

In [6]:
print(torch.__version__)

1.10.2


In [7]:
#We are using pytroch on CPU
#To verify that we are working on CPU

torch.cuda.is_available()

False

In [8]:
#We are using cpu.
#We are using to follow the general coding manner

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [10]:
Initial_tensor = torch.tensor([[1,2,3],[11,22,33]])
Initial_tensor

tensor([[ 1,  2,  3],
        [11, 22, 33]])

In [11]:
Initial_tensor.dtype

torch.int64

In [12]:
Initial_tensor.device

device(type='cpu')

### shape of the Tensor

In [22]:
Initial_tensor.shape

torch.Size([2, 3])

while doing the BackPropagation , will we require this tensor or not? we can check this via function requires_grad

In [23]:
Initial_tensor.requires_grad

False

In [24]:
tensor = torch.tensor([[1,2,3],[11,22,33]],dtype=torch.float,device=device,requires_grad=True)
tensor

tensor([[ 1.,  2.,  3.],
        [11., 22., 33.]], requires_grad=True)

### Checking the default data type

In [25]:
tensor.dtype

torch.float32

In [26]:
tensor.device

device(type='cpu')

In [27]:
tensor.requires_grad

True

### Other commonly used Tensors

In [28]:
empty_tensor = torch.empty(size=(3,3))
empty_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [30]:
zero_tensor = torch.zeros(size=(3,3))
zero_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [31]:
ones_tensor = torch.ones(size=(3,3))
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [32]:
random_tensor = torch.rand(size=(3,3))
random_tensor

tensor([[0.5991, 0.5470, 0.3962],
        [0.5098, 0.9266, 0.2389],
        [0.1023, 0.6826, 0.7313]])

In [33]:
identity_tensor = torch.eye(3)
identity_tensor

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [34]:
arange_tensor = torch.arange(start=0,end=7,step=1)
arange_tensor

tensor([0, 1, 2, 3, 4, 5, 6])

In [36]:
linspace_tensor = torch.linspace(start=0,end=7,steps=4)
linspace_tensor

tensor([0.0000, 2.3333, 4.6667, 7.0000])

In [37]:
normal_dist_tensor = torch.rand(size=(3,4)).normal_(mean=0,std=1)
normal_dist_tensor

tensor([[-0.2924, -0.2975,  0.3969, -1.5535],
        [-0.2796, -0.5728, -0.0850, -0.8105],
        [ 1.5558, -0.5581, -0.3991,  0.1502]])

In [40]:
uniform_dist_tensor = torch.rand(size=(3,4)).uniform_(3,6)
uniform_dist_tensor

tensor([[4.2242, 5.9219, 4.4512, 4.5396],
        [5.4885, 3.0079, 4.9478, 5.5124],
        [4.6874, 4.7506, 4.3705, 5.6374]])

In [41]:
diagonal_tensor = torch.diag(torch.ones(5))
diagonal_tensor

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [42]:
diagonal_tensor = torch.diag(5*torch.ones(5))
diagonal_tensor

tensor([[5., 0., 0., 0., 0.],
        [0., 5., 0., 0., 0.],
        [0., 0., 5., 0., 0.],
        [0., 0., 0., 5., 0.],
        [0., 0., 0., 0., 5.]])

# Conversions to Different Data Types

In [56]:
y = torch.arange(4)
y

tensor([0, 1, 2, 3])

In [57]:
y.bool()

tensor([False,  True,  True,  True])

In [58]:
y.int()

tensor([0, 1, 2, 3], dtype=torch.int32)

In [59]:
y.short() #int16

tensor([0, 1, 2, 3], dtype=torch.int16)

In [60]:
y.long()

tensor([0, 1, 2, 3])

In [61]:
y.half() #float 16 

tensor([0., 1., 2., 3.], dtype=torch.float16)

In [62]:
y.float() #float 32

tensor([0., 1., 2., 3.])

In [63]:
y.double() #float 64

tensor([0., 1., 2., 3.], dtype=torch.float64)

In [64]:
np_array = np.array([[1,2,3],[1,2,3]])
np_array

array([[1, 2, 3],
       [1, 2, 3]])

In [65]:
tensor=torch.from_numpy(np_array)

In [66]:
tensor.numpy()

array([[1, 2, 3],
       [1, 2, 3]])

# Mathematical Operations

In [68]:
x = torch.arange(start=10,end=20,step=4)
y = torch.arange(start=5,end=15,step=4)

x.shape,y.shape

(torch.Size([3]), torch.Size([3]))

In [70]:
x

tensor([10, 14, 18])

In [71]:
y

tensor([ 5,  9, 13])

In [69]:
x+y

tensor([15, 23, 31])

In [72]:
#Element wise multiplication

x*y

tensor([ 50, 126, 234])

In [73]:
x-y

tensor([5, 5, 5])

In [74]:
#Element wise divison
x/y

tensor([2.0000, 1.5556, 1.3846])

In [75]:
z = torch.ones(3)
z

tensor([1., 1., 1.])

In [76]:
z=z+x
z

tensor([11., 15., 19.])

In [77]:
#inplace addition

z.add_(x)
z

tensor([21., 29., 37.])

In [78]:
x.pow(2)

tensor([100, 196, 324])

In [79]:
x**2

tensor([100, 196, 324])

In [80]:
x>0

tensor([True, True, True])

In [81]:
#Matrix Multiplication

a = torch.rand(size=(3,5))
b = torch.rand(size=(5,4))

a @ b


tensor([[1.2831, 1.3384, 1.9983, 0.8529],
        [1.1017, 0.6390, 1.4694, 0.7476],
        [1.2445, 0.9890, 2.1799, 1.2641]])

In [83]:
#Alternative approch for matrix multiplication

a.matmul(b)

tensor([[1.2831, 1.3384, 1.9983, 0.8529],
        [1.1017, 0.6390, 1.4694, 0.7476],
        [1.2445, 0.9890, 2.1799, 1.2641]])

In [85]:
A = torch.rand((3,3))
A.matrix_exp()

tensor([[1.4703, 1.3094, 0.6793],
        [0.2504, 1.9847, 1.0057],
        [0.7023, 2.0825, 2.5454]])

In [86]:
A.matrix_power(2)

tensor([[0.2010, 0.6886, 0.5733],
        [0.2294, 0.7095, 0.5658],
        [0.4044, 1.2988, 1.0371]])

In [87]:
#Dot product of two tensors
torch.dot(x,y)

tensor(410)

In [88]:
#Broadcasting

A

tensor([[0.2944, 0.7247, 0.1993],
        [0.0587, 0.3846, 0.5264],
        [0.3600, 0.9860, 0.6681]])

In [89]:
A + 1

tensor([[1.2944, 1.7247, 1.1993],
        [1.0587, 1.3846, 1.5264],
        [1.3600, 1.9860, 1.6681]])

In [90]:
A - 1

tensor([[-0.7056, -0.2753, -0.8007],
        [-0.9413, -0.6154, -0.4736],
        [-0.6400, -0.0140, -0.3319]])

In [91]:
A*5

tensor([[1.4720, 3.6234, 0.9967],
        [0.2935, 1.9229, 2.6319],
        [1.8002, 4.9300, 3.3404]])

In [92]:
A.shape

torch.Size([3, 3])

In [93]:
C = torch.ones((1,3))

In [94]:
#1s are substracted from each of the rows

A - C

tensor([[-0.7056, -0.2753, -0.8007],
        [-0.9413, -0.6154, -0.4736],
        [-0.6400, -0.0140, -0.3319]])

In [95]:
A + C

tensor([[1.2944, 1.7247, 1.1993],
        [1.0587, 1.3846, 1.5264],
        [1.3600, 1.9860, 1.6681]])

In [96]:
D = torch.ones(3,1)

In [98]:
#Column wise subtractions for 1s
A - D

tensor([[-0.7056, -0.2753, -0.8007],
        [-0.9413, -0.6154, -0.4736],
        [-0.6400, -0.0140, -0.3319]])

In [99]:
A + D

tensor([[1.2944, 1.7247, 1.1993],
        [1.0587, 1.3846, 1.5264],
        [1.3600, 1.9860, 1.6681]])

In [100]:
A

tensor([[0.2944, 0.7247, 0.1993],
        [0.0587, 0.3846, 0.5264],
        [0.3600, 0.9860, 0.6681]])

In [101]:
D

tensor([[1.],
        [1.],
        [1.]])

In [102]:
torch.sum(D)

tensor(3.)

In [103]:
torch.sum(A)

tensor(4.2022)

In [104]:
A

tensor([[0.2944, 0.7247, 0.1993],
        [0.0587, 0.3846, 0.5264],
        [0.3600, 0.9860, 0.6681]])

In [105]:
torch.max(A)

tensor(0.9860)

In [106]:
torch.min(A)

tensor(0.0587)

In [107]:
torch.mean(A)

tensor(0.4669)

In [108]:
# Find the min values in each row

torch.min(A,dim=1)

torch.return_types.min(
values=tensor([0.1993, 0.0587, 0.3600]),
indices=tensor([2, 0, 0]))

In [109]:
torch.max(A,dim=1)

torch.return_types.max(
values=tensor([0.7247, 0.5264, 0.9860]),
indices=tensor([1, 2, 1]))

In [110]:
#Find the min values in each col

torch.min(A,dim=0)

torch.return_types.min(
values=tensor([0.0587, 0.3846, 0.1993]),
indices=tensor([1, 1, 0]))

In [112]:
torch.abs(-A)

tensor([[0.2944, 0.7247, 0.1993],
        [0.0587, 0.3846, 0.5264],
        [0.3600, 0.9860, 0.6681]])

In [113]:
torch.argmax(A)

tensor(7)

In [114]:
torch.argmin(A)

tensor(3)

In [115]:
#Find the index of the max value row wise
torch.argmax(A,dim=1)

tensor([1, 2, 1])

In [116]:
#Find the index of the min value row wise
torch.argmin(A,dim=1)

tensor([2, 0, 0])

In [117]:
#Find the index of the min value col wise
torch.argmin(A,dim=0)

tensor([1, 1, 0])

In [118]:
#Find the index of the max value col wise
torch.argmax(A,dim=0)

tensor([2, 2, 2])

In [119]:
#Find the mean row wise
torch.mean(A,dim=1)

tensor([0.4061, 0.3232, 0.6714])

In [120]:
#Find the mean col wise
torch.mean(A,dim=0)

tensor([0.2377, 0.6984, 0.4646])

In [121]:
A

tensor([[0.2944, 0.7247, 0.1993],
        [0.0587, 0.3846, 0.5264],
        [0.3600, 0.9860, 0.6681]])

In [123]:
D = torch.ones(A.shape)
D

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [125]:
#Comparing A and D element wise
torch.eq(A,D)

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [126]:
A

tensor([[0.2944, 0.7247, 0.1993],
        [0.0587, 0.3846, 0.5264],
        [0.3600, 0.9860, 0.6681]])

In [127]:
#Each row sorted
torch.sort(A)

torch.return_types.sort(
values=tensor([[0.1993, 0.2944, 0.7247],
        [0.0587, 0.3846, 0.5264],
        [0.3600, 0.6681, 0.9860]]),
indices=tensor([[2, 0, 1],
        [0, 1, 2],
        [0, 2, 1]]))

In [129]:
#Each col sorted
torch.sort(A,dim=0)

torch.return_types.sort(
values=tensor([[0.0587, 0.3846, 0.1993],
        [0.2944, 0.7247, 0.5264],
        [0.3600, 0.9860, 0.6681]]),
indices=tensor([[1, 1, 0],
        [0, 0, 1],
        [2, 2, 2]]))

In [130]:
#Clamp the tensor if the values is below the threshold values -> value = threshold
torch.clamp(A,min=0.5)

tensor([[0.5000, 0.7247, 0.5000],
        [0.5000, 0.5000, 0.5264],
        [0.5000, 0.9860, 0.6681]])

In [131]:
A

tensor([[0.2944, 0.7247, 0.1993],
        [0.0587, 0.3846, 0.5264],
        [0.3600, 0.9860, 0.6681]])

# Indexing , Slicing, Concatenation and Reshaping Operations

In [132]:
Tensor = torch.rand(size=(3,4))
Tensor

tensor([[0.3171, 0.8870, 0.5975, 0.7841],
        [0.8962, 0.7143, 0.9882, 0.5780],
        [0.9268, 0.9957, 0.6012, 0.7536]])

In [133]:
#Tensor[row,cols,steps]
# row - > start:stop:step
# col - > start:stop:step


Tensor[0,:]

tensor([0.3171, 0.8870, 0.5975, 0.7841])

In [134]:
Tensor[:,0]

tensor([0.3171, 0.8962, 0.9268])

In [135]:
Tensor[0:2,0:3]

tensor([[0.3171, 0.8870, 0.5975],
        [0.8962, 0.7143, 0.9882]])

In [136]:
Tensor[0,0]

tensor(0.3171)

In [137]:
Tensor[0,0] = .8

In [138]:
Tensor

tensor([[0.8000, 0.8870, 0.5975, 0.7841],
        [0.8962, 0.7143, 0.9882, 0.5780],
        [0.9268, 0.9957, 0.6012, 0.7536]])

In [140]:
TensorX = torch.rand(size=(3,4))
TensorY = torch.rand(size=(3,4))

In [141]:
#Horizontal Concatenation

torch.cat((TensorX,TensorY),dim=1)

tensor([[0.0728, 0.4353, 0.4237, 0.6530, 0.3772, 0.9652, 0.4505, 0.8595],
        [0.5642, 0.5375, 0.3008, 0.3903, 0.1763, 0.3635, 0.2138, 0.2698],
        [0.7248, 0.6836, 0.0108, 0.5761, 0.2924, 0.9918, 0.6179, 0.2334]])

In [144]:
#Vertical concatenation

torch.cat((TensorX,TensorY),dim=0)

tensor([[0.0728, 0.4353, 0.4237, 0.6530],
        [0.5642, 0.5375, 0.3008, 0.3903],
        [0.7248, 0.6836, 0.0108, 0.5761],
        [0.3772, 0.9652, 0.4505, 0.8595],
        [0.1763, 0.3635, 0.2138, 0.2698],
        [0.2924, 0.9918, 0.6179, 0.2334]])

In [145]:
TensorX.shape

torch.Size([3, 4])

In [146]:
#Number of elements should match
Tensor.reshape(2,6) 

tensor([[0.8000, 0.8870, 0.5975, 0.7841, 0.8962, 0.7143],
        [0.9882, 0.5780, 0.9268, 0.9957, 0.6012, 0.7536]])

In [148]:
TensorX.reshape(1,12)

tensor([[0.0728, 0.4353, 0.4237, 0.6530, 0.5642, 0.5375, 0.3008, 0.3903, 0.7248,
         0.6836, 0.0108, 0.5761]])

In [149]:
TensorX.reshape(12,1)

tensor([[0.0728],
        [0.4353],
        [0.4237],
        [0.6530],
        [0.5642],
        [0.5375],
        [0.3008],
        [0.3903],
        [0.7248],
        [0.6836],
        [0.0108],
        [0.5761]])

In [151]:
#Flattening Operations

TensorX.view(-1)

tensor([0.0728, 0.4353, 0.4237, 0.6530, 0.5642, 0.5375, 0.3008, 0.3903, 0.7248,
        0.6836, 0.0108, 0.5761])

In [153]:
TensorX.view(-1).shape

torch.Size([12])

In [156]:
#Batch Flattening
batch = 16
torch.rand((batch,2,5)).view(batch,-1)

tensor([[0.9070, 0.7919, 0.6132, 0.2486, 0.1355, 0.1992, 0.8709, 0.1780, 0.8649,
         0.5660],
        [0.5291, 0.9455, 0.9383, 0.9605, 0.5071, 0.4900, 0.6949, 0.8131, 0.3487,
         0.7767],
        [0.3289, 0.1073, 0.1725, 0.4811, 0.9382, 0.7643, 0.8693, 0.9120, 0.1529,
         0.8120],
        [0.2651, 0.2259, 0.0795, 0.9197, 0.2269, 0.2513, 0.2331, 0.9293, 0.4156,
         0.0407],
        [0.6019, 0.9094, 0.0493, 0.2362, 0.3184, 0.1185, 0.4351, 0.3922, 0.0993,
         0.8252],
        [0.0328, 0.9406, 0.3290, 0.0775, 0.9919, 0.0227, 0.5816, 0.6349, 0.2954,
         0.9222],
        [0.0491, 0.7471, 0.4863, 0.2628, 0.4760, 0.0741, 0.8434, 0.2253, 0.7044,
         0.0218],
        [0.0708, 0.9842, 0.3915, 0.7418, 0.7840, 0.8353, 0.9170, 0.0536, 0.1779,
         0.2246],
        [0.4663, 0.6123, 0.8727, 0.6585, 0.8743, 0.4191, 0.7356, 0.5791, 0.6852,
         0.0156],
        [0.6946, 0.6536, 0.0849, 0.0305, 0.0345, 0.0888, 0.0292, 0.4891, 0.2259,
         0.2882],
        [0