In [ ]:
!pip3 install torch==1.2.0+cu92 torchvision==0.4.0+cu92 -f https://download.pytorch.org/whl/torch_stable.html

Looking in links: https://download.pytorch.org/whl/torch_stable.html
     |████████████████████████████████| 663.1 MB 1.6 kB/s 
     |████████████████████████████████| 8.8 MB 35.5 MB/s 
  Attempting uninstall: torch
    Found existing installation: torch 1.11.0+cu113
    Uninstalling torch-1.11.0+cu113:
      Successfully uninstalled torch-1.11.0+cu113
  Attempting uninstall: torchvision
    Found existing installation: torchvision 0.12.0+cu113
    Uninstalling torchvision-0.12.0+cu113:
      Successfully uninstalled torchvision-0.12.0+cu113
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchtext 0.12.0 requires torch==1.11.0, but you have torch 1.2.0+cu92 which is incompatible.
torchaudio 0.11.0+cu113 requires torch==1.11.0, but you have torch 1.2.0+cu92 which is incompatible.


In [ ]:
import torch

In [ ]:
torch.cuda.is_available()

True

In [ ]:
print(torch.rand(2,2))

tensor([[0.8236, 0.0247],
        [0.3733, 0.7176]])


Tensor is both a container for numbers as well as set of rules that define transformations between tensors that produce new tensors.Rank corresponds to the dimensional space of a tensor.

In [ ]:
x = torch.tensor([[0,0,1],[1,1,1],[0,0,0]])
x[0][0] = 5
x

tensor([[5, 0, 1],
        [1, 1, 1],
        [0, 0, 0]])

Creating zeros

In [ ]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

Adding Tensors

In [ ]:
torch.ones(1,2) + torch.ones(1,2)

tensor([[2., 2.]])

Tensors can live in the CPU or on the GPU and can be copied between devies by using to() function

In [ ]:
cpu_tensor = torch.rand(2)

In [ ]:
cpu_tensor.device

device(type='cpu')

In [ ]:
gpu_tensor = cpu_tensor.to("cuda")

In [ ]:
gpu_tensor.device

device(type='cuda', index=0)

Maximum item in a tensor as well as the index that contains the maximum value.

In [ ]:
random_tensor=torch.rand(2,2)
random_tensor

tensor([[0.8466, 0.2268],
        [0.9473, 0.8738]])

In [ ]:
random_tensor.max()

tensor(0.9473)

In [ ]:
random_tensor.argmax()

tensor(2)

Changing DataType Long Tensor to Float Tensor

In [ ]:
long_tensor = torch.tensor([[0,0,1],[1,1,1],[0,0,0]])
long_tensor.type()

'torch.LongTensor'

In [ ]:
float_tensor = torch.tensor([[0,0,1],[1,1,1],[0,0,0]]).to(dtype = torch.float32)
float_tensor.type()

'torch.FloatTensor'

Most functions that operate on a tensor and return a tensor create a new tensor to store the result.If you wnat to save a memory , look to see if an in-place function , which should be the same name as the original functions but with an appended underscore(_)

In [ ]:
random_tensor = torch.rand(2,2)
random_tensor.log2_()

tensor([[-0.6765, -0.6888],
        [-2.2102, -0.9513]])

In [ ]:
random_tensor

tensor([[-0.6765, -0.6888],
        [-2.2102, -0.9513]])

Reshape the tensor

In [ ]:
flat_tensor = torch.rand(784)
flat_tensor.shape

torch.Size([784])

In [ ]:
viewed_tensor = flat_tensor.view(1,28,28)
viewed_tensor.shape
viewed_tensor.type()

'torch.FloatTensor'

In [ ]:
reshaped_tensor = flat_tensor.reshape(1,28,28)
reshaped_tensor.shape

torch.Size([1, 28, 28])

##Difference between view and reshape

View operates as a view on the original tensor , if the underlying data is changes , the view wil change too. view can throw errors if the required view is not contiguous.It does not share the same block of memory it would occupy if a new tensor of the requred shape was created from scratch.If this happensm call tensor.contiguous() before you can use view(). Reshape does all this behind the scenes.

Rearrange the dimensions of a tensor

In [ ]:
hwc_tensor = torch.rand(640,480,3)
chw_tensor = hwc_tensor.permute(2,0,1)
chw_tensor.shape

torch.Size([3, 640, 480])